### ISSUE TITLE
Add MSX and LSKonline

### ISSUE THREAD

**Issue by Biiian** [spyfly/TUD-AutoLogin#1]
First of all, this script is very helpful. It can make Login very simple. Thank you for it. 
But I have unfortunately came up with two problems. 
1. You may forget the online mail portal (https://msx.tu-dresden.de/) and the LSKonline (https://lskonline.tu-dresden.de/). 
2. AutoLogin for selma and HISQIS doesn't work. For HISQIS, I guess, it is because people have to agree something, and then login. For selma, I don't know why.

**Comment by spyfly** [comment]
Hi bianrui96,

For me the [selma](https://selma.tu-dresden.de) and [HISQIS](https://qis.dez.tu-dresden.de/qisserver) AutoLogin work without any issues. If visiting those URLs directly doesn't fix the problem for you, I'd suggest opening a new issue.
