### ISSUE TITLE
Selecting TU Dresden in Opal does not work

### ISSUE THREAD

**Issue by l0drex** [spyfly/TUD-AutoLogin#3]
When Opal is opened for the first time, the school isn't selected which results in an endless error loop because the script tries to login without selecting TU Dresden.

One can bypass this issue by disabling this script, selecting TU Dresden, reactivate the script and reloading the login page.

**Comment by spyfly** [comment]
Thanks for reporting the issue and proposing a solution. I've removed the hardcoded login index and replaced it with your proposed solution.

I didn't feel comfortable redirecting the users however, as you've proposed in #4, so instead I used querySelectors to merge the both login procedures.
