### ISSUE TITLE
Request: add some feature of TU-AutoLogin to TUfast

### ISSUE THREAD

**Issue by OliEfr** [spyfly/TUD-AutoLogin#5]
Hey, I just stumbled across your TUD-AutoLogin scripts. Great work! :)

Not sure whether you know already, but there is also [TUfast](https://github.com/TUfast-TUD/TUfast_TUD), which also features auto-login functionality - among some other productivity tools.

I notice, that your tool supports some more services than TUfast does atm. It would be great if you find the time to support TUfast and maybe create a PR! :)

LG, Oli

**Comment by DrJume** [comment]
@OliEfr If you ask others to contribute to your project, license it please at least under an OpenSource license.

**Comment by OliEfr** [comment]
Hey @DrJume and thanks for letting me know :)

I hope though, not assigning a license yet haven't witheld anyone from contributing. It has been my first OS-Project and I wasn't aware of the licences at the beginning. I havent found time to dive deeper into the topic and assign an appropriate licence. I will do so asap!

**Comment by spyfly** [comment]
@OliEfr your request seems to be completely unrelated to this project, as it does not propose any ideas or changes related to this project. Therefore I am closing this issue. 
I'd suggest opening a issue in your own project.

**Comment by OliEfr** [comment]
@spyfly yes, I should have opened the issue in TUfast. Btw I heard, that ZIH might switch to a new login interface for SAML. [tex.zih.tu-dresden.de](https://tex.zih.tu-dresden.de/saml/login) has already implement it.
I still think, that we should combine our projects ;)

EDIT: Alright just noticed they are exactly the same apart from styling.
